import { useEffect, useMemo, useState } from 'react';

const Icon = ({ children }) => <span className="material-symbols-rounded">{children}</span>;
const dateInput = value => value ? new Date(value).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10);
const initials = value => value.split(/\s+/).map(word => word[0]).slice(0, 2).join('').toUpperCase();
const roles = { DIRECTOR: 'Director', COACH: 'Entrenador', MONITOR: 'Monitor' };

function useLoad(load, deps = []) {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  const refresh = async () => { setError(''); try { setData(await load()); } catch (err) { setError(err.message); } };
  useEffect(() => { void refresh(); }, deps);
  return { data, error, refresh };
}
function Modal({ title, close, children }) { return <div className="modal-backdrop" onMouseDown={event => event.target === event.currentTarget && close()}><section className="card modal modal-wide"><div className="modal-head"><h2>{title}</h2><button className="icon-close" onClick={close}><Icon>close</Icon></button></div>{children}</section></div>; }
function Error({ text }) { return <p className="error">{text}</p>; }
function Loading() { return <div className="loading">Cargando…</div>; }
function Button({ children, ...props }) { return <button className="secondary" {...props}>{children}</button>; }
function Field({ label, children }) { return <label className="field"><span className="eyebrow">{label}</span><span className="input-wrap">{children}</span></label>; }

export function TeamWorkspace({ api, director, notify }) {
  const { data: teams, error, refresh } = useLoad(() => api('/teams'));
  const [selected, setSelected] = useState(null); const [creating, setCreating] = useState(false); const [categories, setCategories] = useState(false);
  if (error) return <Error text={error} />; if (!teams) return <Loading />;
  return <><header className="page-head"><div><span className="eyebrow">GESTIÓN DEPORTIVA</span><h1>Tus equipos</h1><p className="subtitle">Plantel, agenda, asistencia y planificación deportiva.</p></div><div className="toolbar"><Button onClick={() => setCategories(true)}><Icon>sell</Icon> Categorías</Button>{director && <Button onClick={() => setCreating(true)}><Icon>add</Icon> Crear equipo</Button>}</div></header><div className="grid">{teams.map(team => <button className="card team-card interactive-card" key={team.id} onClick={() => setSelected(team)}><div className="team-mark"><Icon>groups</Icon></div><div><strong>{team.name}</strong><p className="muted">{team.category.name}</p></div><footer>{team._count.players} jugadores</footer></button>)}</div>{!teams.length && <div className="card empty">Todavía no hay equipos.</div>}{selected && <TeamDetail api={api} team={selected} director={director} close={() => setSelected(null)} notify={notify} changed={refresh} />}{creating && <TeamEditor api={api} close={() => setCreating(false)} done={() => { setCreating(false); refresh(); notify('Equipo creado'); }} />}{categories && <CategoryManager api={api} close={() => setCategories(false)} />}</>;
}

function TeamEditor({ api, team, close, done }) {
  const { data: categories } = useLoad(() => api('/categories'));
  const [error, setError] = useState('');
  if (!categories) return <Modal title={team ? 'Editar equipo' : 'Crear equipo'} close={close}><Loading /></Modal>;
  return <Modal title={team ? 'Editar equipo' : 'Crear equipo'} close={close}><form className="modal-form" onSubmit={async event => { event.preventDefault(); try { await api(team ? `/teams/${team.id}` : '/teams', { method: team ? 'PATCH' : 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); done(); } catch (err) { setError(err.message); } }}><Field label="NOMBRE"><input name="name" required defaultValue={team?.name} /></Field><Field label="CATEGORÍA"><select name="categoryId" defaultValue={team?.category.id}>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Error text={error} /><button className="primary">Guardar</button></form></Modal>;
}

function CategoryManager({ api, close }) {
  const { data: categories, error, refresh } = useLoad(() => api('/categories'));
  const [name, setName] = useState('');
  return <Modal title="Categorías" close={close}>{!categories ? <Loading /> : <div className="stack"><form className="inline-form" onSubmit={async event => { event.preventDefault(); try { await api('/categories', { method: 'POST', body: JSON.stringify({ name }) }); setName(''); refresh(); } catch {} }}><input value={name} onChange={e => setName(e.target.value)} placeholder="Nueva categoría" required /><Button><Icon>add</Icon></Button></form>{error && <Error text={error} />}{categories.map(category => <div className="list-row" key={category.id}><strong>{category.name}</strong><div><button className="text-action" onClick={async () => { const name = prompt('Nuevo nombre', category.name); if (name?.trim()) { try { await api(`/categories/${category.id}`, { method:'PATCH', body:JSON.stringify({ name }) }); refresh(); } catch (err) { alert(err.message); } } }}>Renombrar</button><button className="text-action danger" onClick={async () => { if (confirm(`¿Archivar ${category.name}?`)) { try { await api(`/categories/${category.id}`, { method: 'DELETE' }); refresh(); } catch (err) { alert(err.message); } } }}>Archivar</button></div></div>)}</div>}</Modal>;
}

function TeamDetail({ api, team, director, close, notify, changed }) {
  const [tab, setTab] = useState('plantel'); const [editor, setEditor] = useState(false);
  const tabs = [['plantel', 'groups', 'Plantel'], ['agenda', 'calendar_month', 'Agenda'], ['planificacion', 'event_note', 'Planificación'], ['asistencia', 'fact_check', 'Asistencia'], ['estadisticas', 'bar_chart', 'Estadísticas'], ['plan', 'target', 'Plan']]; if (director) tabs.push(['staff', 'manage_accounts', 'Personal']);
  return <Modal title={team.name} close={close}><div className="modal-toolbar"><div className="tab-bar">{tabs.map(([key, icon, label]) => <button className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}><Icon>{icon}</Icon>{label}</button>)}</div>{director && <div className="toolbar"><Button onClick={() => setEditor(true)}><Icon>edit</Icon></Button><button className="text-action danger" onClick={async () => { if(confirm(`¿Archivar ${team.name}?`)){ await api(`/teams/${team.id}`,{method:'DELETE'}); changed(); close(); notify('Equipo archivado'); } }}>Archivar</button></div>}</div>{tab === 'plantel' && <Roster api={api} team={team} notify={notify} />}{tab === 'agenda' && <Events api={api} team={team} notify={notify} />}{tab === 'planificacion' && <TrainingPlans api={api} team={team} notify={notify} />}{tab === 'asistencia' && <Attendance api={api} team={team} notify={notify} />}{tab === 'estadisticas' && <Statistics api={api} team={team} />}{tab === 'plan' && <Plan api={api} team={team} notify={notify} />}{tab === 'staff' && <TeamStaff api={api} team={team} notify={notify} />}{editor && <TeamEditor api={api} team={team} close={() => setEditor(false)} done={() => { setEditor(false); changed(); notify('Equipo actualizado'); }} />}</Modal>;
}

function TrainingPlans({ api, team, notify }) { const { data, refresh } = useLoad(() => api(`/teams/${team.id}/training-plans`)); const [editing, setEditing] = useState(null); if (!data) return <Loading />; return <div className="stack"><Button onClick={() => setEditing({})}><Icon>add</Icon> Planificar entrenamiento</Button>{data.length ? data.map(plan => <article className="card training-card" key={plan.id}><div><span className="eyebrow">{new Date(plan.scheduledFor).toLocaleDateString('es-AR')}</span><strong>{plan.title}</strong><p>{plan.mainObjective}</p><small>Intensidad {plan.intensity}/5 · Carga {plan.cognitiveLoad === 'LOW' ? 'baja' : plan.cognitiveLoad === 'HIGH' ? 'alta' : 'media'}</small></div><div><button className="text-action" onClick={() => setEditing(plan)}>Editar</button><button className="text-action danger" onClick={async()=>{if(confirm('¿Eliminar planificación?')){await api(`/training-plans/${plan.id}`,{method:'DELETE'});refresh();notify('Planificación eliminada');}}}>Eliminar</button></div></article>) : <div className="empty">Todavía no hay entrenamientos planificados.</div>}{editing && <TrainingPlanEditor api={api} team={team} plan={editing.id ? editing : null} close={()=>setEditing(null)} done={()=>{setEditing(null);refresh();notify('Planificación guardada');}} />}</div>; }
function TrainingPlanEditor({ api, team, plan, close, done }) { const [error,setError]=useState(''); return <Modal title={plan?'Editar entrenamiento':'Planificar entrenamiento'} close={close}><form className="modal-form" onSubmit={async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));data.intensity=Number(data.intensity);try{await api(plan?`/training-plans/${plan.id}`:`/teams/${team.id}/training-plans`,{method:plan?'PATCH':'POST',body:JSON.stringify(data)});done();}catch(err){setError(err.message)}}}><Field label="NOMBRE DE LA SESIÓN"><input name="title" required defaultValue={plan?.title} placeholder="Ej. Transición defensiva" /></Field><Field label="FECHA"><input name="scheduledFor" type="date" required defaultValue={dateInput(plan?.scheduledFor)} /></Field><Field label="OBJETIVO PRINCIPAL"><input name="mainObjective" required defaultValue={plan?.mainObjective} placeholder="Ej. Mejorar balance defensivo" /></Field><label className="field"><span className="eyebrow">OBJETIVOS SECUNDARIOS</span><textarea name="secondaryGoals" defaultValue={plan?.secondaryGoals||''} /></label><Field label="INTENSIDAD FÍSICA (1–5)"><select name="intensity" defaultValue={plan?.intensity||3}>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n} · {['Muy baja','Baja','Media','Alta','Máxima'][n-1]}</option>)}</select></Field><Field label="CARGA COGNITIVA"><select name="cognitiveLoad" defaultValue={plan?.cognitiveLoad||'MEDIUM'}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option></select></Field><label className="field"><span className="eyebrow">EJERCICIOS Y TIEMPOS</span><textarea name="exercises" defaultValue={plan?.exercises||''} placeholder={'1. Activación — 10 min\n2. Ejercicio principal — 25 min'} /></label><label className="field"><span className="eyebrow">NOTAS</span><textarea name="notes" defaultValue={plan?.notes||''} /></label><Error text={error}/><button className="primary">Guardar planificación</button></form></Modal>; }

function Roster({ api, team, notify }) {
  const { data: players, error, refresh } = useLoad(() => api('/players'));
  const [creating, setCreating] = useState(false); const [importing, setImporting] = useState(false); const [selected, setSelected] = useState(null);
  if (!players) return <Loading />; const roster = players.filter(player => player.teams.some(item => item.teamId === team.id));
  function exportCsv() { const lines = [['Nombre', 'Nacimiento'], ...roster.map(p => [p.name, p.birthDate])].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\r\n'); const url = URL.createObjectURL(new Blob([`\uFEFF${lines}`], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `plantel-${team.name.toLowerCase().replaceAll(' ', '-')}.csv`; link.click(); URL.revokeObjectURL(url); }
  return <div className="stack"><div className="toolbar"><Button onClick={() => setCreating(true)}><Icon>person_add</Icon> Jugador</Button><Button onClick={() => setImporting(true)}><Icon>upload_file</Icon> Importar CSV</Button><Button onClick={exportCsv}><Icon>download</Icon> CSV</Button></div>{error && <Error text={error} />}{roster.map(player => <button className="list-row selectable" key={player.id} onClick={() => setSelected(player)}><span className="avatar">{initials(player.name)}</span><span><strong>{player.name}</strong><small>{player.birthDate}</small></span><Icon>chevron_right</Icon></button>)}{!roster.length && <div className="empty">No hay jugadores en este equipo.</div>}{creating && <PlayerEditor api={api} team={team} close={() => setCreating(false)} done={() => { setCreating(false); refresh(); notify('Jugador creado'); }} />}{selected && <PlayerDetail api={api} player={selected} teams={players} close={() => setSelected(null)} refresh={refresh} notify={notify} />}{importing && <ImportPlayers api={api} team={team} close={() => setImporting(false)} done={() => { setImporting(false); refresh(); notify('Importación completada'); }} />}</div>;
}

export function PlayerWorkspace({ api, notify }) {
  const { data: players, error, refresh } = useLoad(() => api('/players'));
  const { data: teams } = useLoad(() => api('/teams'));
  const [query, setQuery] = useState(''); const [teamFilter, setTeamFilter] = useState(''); const [selected, setSelected] = useState(null); const [creating, setCreating] = useState(false);
  if (!players || !teams) return <Loading />;
  const visible = players.filter(player => player.name.toLowerCase().includes(query.toLowerCase()) && (!teamFilter || player.teams.some(item => item.teamId === teamFilter)));
  return <><header className="page-head"><div><span className="eyebrow">PLANTEL</span><h1>Jugadores</h1><p className="subtitle">Directorio, ficha deportiva y seguimientos.</p></div><div className="toolbar"><input className="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por nombre" /><select className="secondary" value={teamFilter} onChange={e => setTeamFilter(e.target.value)}><option value="">Todos los equipos</option>{teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select><Button onClick={() => setCreating(true)}><Icon>person_add</Icon> Jugador</Button></div></header><Error text={error} /><div className="list">{visible.map(player => <button className="card list-row selectable" key={player.id} onClick={() => setSelected(player)}><span className="avatar">{initials(player.name)}</span><span><strong>{player.name}</strong><small>{player.position || 'Sin posición'} · {player.teams.length} equipo(s)</small></span><Icon>chevron_right</Icon></button>)}</div>{!visible.length && <div className="card empty">No hay jugadores que coincidan.</div>}{selected && <PlayerDetail api={api} player={selected} teams={teams} close={() => setSelected(null)} refresh={refresh} notify={notify} />}{creating && <PlayerEditor api={api} teams={teams} close={() => setCreating(false)} done={() => { setCreating(false); refresh(); notify('Jugador creado'); }} />}</>;
}

function ImportPlayers({ api, team, close, done }) {
  const [rows, setRows] = useState(''); const [fileName, setFileName] = useState(''); const [error, setError] = useState('');
  const isoDate = value => {
    const clean = value.trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(clean)) return clean;
    const parts = clean.split('/');
    return parts.length === 3 && parts[0].length === 2 ? `${parts[2]}-${parts[1]}-${parts[0]}` : '';
  };
  const normalizeName = value => value.trim().replace(/\s+/g, ' ').replace(/^([^,]+),\s*(.+)$/, '$2 $1').trim();
  const parse = value => {
    const lines = value.replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean);
    if (!lines.length) return [];
    const separator = lines[0].includes(';') ? ';' : ',';
    const cells = line => line.split(separator).map(item => item.trim().replace(/^"|"$/g, ''));
    const header = cells(lines[0]).map(value => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase());
    const nameIndex = header.findIndex(value => value === 'NOMBRE' || value === 'NOMBRE COMPLETO');
    const birthIndex = header.findIndex(value => value === 'FECHA NACIMIENTO' || value === 'FECHA DE NACIMIENTO' || value === 'NACIMIENTO');
    const typeIndex = header.findIndex(value => value === 'TIPO');
    const statusIndex = header.findIndex(value => value === 'ESTADO LICENCIA' || value === 'ESTADO');
    const removalIndex = header.findIndex(value => value === 'BAJA');
    if (nameIndex >= 0 && birthIndex >= 0) return lines.slice(1).map(cells).filter(row => {
      const type = typeIndex >= 0 ? row[typeIndex]?.toUpperCase() : 'JUGADOR';
      const status = statusIndex >= 0 ? row[statusIndex]?.toUpperCase() : '';
      return type === 'JUGADOR' && status !== 'BAJA' && !(removalIndex >= 0 && row[removalIndex]);
    }).map(row => ({ name: normalizeName(row[nameIndex] || ''), birthDate: isoDate(row[birthIndex] || '') })).filter(player => player.name && /^\d{4}-\d{2}-\d{2}$/.test(player.birthDate));
    return lines.map(cells).filter(row => row.length >= 2).map(([name, birthDate]) => ({ name: normalizeName(name), birthDate: isoDate(birthDate) })).filter(player => player.name && /^\d{4}-\d{2}-\d{2}$/.test(player.birthDate));
  };
  return <Modal title="Importar jugadores" close={close}><form className="modal-form" onSubmit={async event => { event.preventDefault(); const players = parse(rows); if (!players.length) return setError('No encontramos jugadores activos con nombre y fecha de nacimiento válidos.'); try { const result = await api(`/teams/${team.id}/players/import`, { method: 'POST', body: JSON.stringify({ players }) }); alert(`Creados: ${result.created}. Omitidos: ${result.skipped}.`); done(); } catch (err) { setError(err.message); } }}><p className="notice">Compatible con planillas de licencias: importa <strong>JUGADOR</strong> activos y excluye entrenadores, trainers y bajas.</p><label className="file-picker"><Icon>upload_file</Icon><span>{fileName || 'Seleccionar archivo CSV'}</span><input type="file" accept=".csv,text/csv" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; const buffer = await file.arrayBuffer(); let text = new TextDecoder('utf-8').decode(buffer); if (text.includes('�')) text = new TextDecoder('windows-1252').decode(buffer); setFileName(file.name); setRows(text); setError(''); }} /></label><textarea rows="9" value={rows} onChange={e => { setRows(e.target.value); setFileName(''); }} placeholder={'NOMBRE;FECHA NACIMIENTO;TIPO\nAPELLIDO, NOMBRE;20/04/2010;JUGADOR'} /><p className="notice">{rows ? `${parse(rows).length} jugador(es) activo(s) válido(s) detectado(s).` : 'Máximo 300 jugadores por importación.'}</p><Error text={error} /><button className="primary">Importar jugadores</button></form></Modal>;
}

function PlayerEditor({ api, team, teams, player, close, done }) {
  const [error, setError] = useState('');
  const fields = [['Posición', 'position'], ['Club actual', 'currentClub'], ['Altura (cm)', 'heightCm', 'number'], ['Peso (kg)', 'weightKg', 'number'], ['Envergadura (cm)', 'wingspanCm', 'number'], ['Salto vertical (cm)', 'verticalJumpCm', 'number'], ['Tiro exterior (1–10)', 'outsideShooting', 'number'], ['Defensa 1v1 (1–10)', 'defenseOneOnOne', 'number'], ['IQ basket (1–10)', 'basketballIQ', 'number']];
  return <Modal title={player ? 'Editar jugador' : 'Crear jugador'} close={close}><form className="modal-form" onSubmit={async event => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); for (const key of ['heightCm', 'weightKg', 'wingspanCm', 'verticalJumpCm', 'outsideShooting', 'defenseOneOnOne', 'basketballIQ']) if (form[key] === '') delete form[key]; else form[key] = Number(form[key]); try { if (player) await api(`/players/${player.id}`, { method: 'PATCH', body: JSON.stringify(form) }); else { form.teamIds = teams ? [...event.currentTarget.elements.teamIds.selectedOptions].map(x => x.value) : [team.id]; await api('/players', { method: 'POST', body: JSON.stringify(form) }); } done(); } catch (err) { setError(err.message); } }}><Field label="NOMBRE"><input name="name" defaultValue={player?.name} required /></Field><Field label="NACIMIENTO"><input name="birthDate" type="date" defaultValue={dateInput(player?.birthDate)} required /></Field>{!player && teams && <Field label="EQUIPOS (MÁXIMO 2)"><select name="teamIds" multiple size="3">{teams.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field>}{fields.map(([label, key, type]) => <Field key={key} label={label}><input name={key} type={type || 'text'} defaultValue={player?.[key] ?? ''} /></Field>)}<label className="field"><span className="eyebrow">OBSERVACIONES DEPORTIVAS</span><textarea name="scoutingNotes" defaultValue={player?.scoutingNotes ?? ''} /></label><Error text={error} /><button className="primary">Guardar</button></form></Modal>;
}

function PlayerDetail({ api, player, teams, close, refresh, notify }) {
  const [view, setView] = useState('perfil'); const [editing, setEditing] = useState(false);
  return <Modal title={player.name} close={close}><div className="tab-bar"><button className={view === 'perfil' ? 'active' : ''} onClick={() => setView('perfil')}>Perfil</button><button className={view === 'seguimiento' ? 'active' : ''} onClick={() => setView('seguimiento')}>Seguimiento</button><button className={view === 'equipos' ? 'active' : ''} onClick={() => setView('equipos')}>Equipos</button></div>{view === 'perfil' && <div className="stack"><Button onClick={() => setEditing(true)}><Icon>edit</Icon> Editar</Button><p className="notice">{player.position || 'Sin posición'} · {player.currentClub || 'Sin club'}</p><p>{player.scoutingNotes || 'Sin observaciones deportivas.'}</p><button className="text-action danger" onClick={async () => { if (confirm('¿Archivar este jugador?')) { await api(`/players/${player.id}`, { method: 'DELETE' }); refresh(); close(); notify('Jugador archivado'); } }}>Archivar jugador</button></div>}{view === 'seguimiento' && <ProgressNotes api={api} player={player} notify={notify} />}{view === 'equipos' && <PlayerTeams api={api} player={player} teams={teams} refresh={refresh} notify={notify} />}{editing && <PlayerEditor api={api} player={player} close={() => setEditing(false)} done={() => { setEditing(false); refresh(); notify('Jugador actualizado'); }} />}</Modal>;
}

function PlayerTeams({ api, player, teams, refresh, notify }) { const memberships = new Set(player.teams.map(x => x.teamId)); return <div className="stack">{teams.map(team => <label className="list-row" key={team.id}><span><strong>{team.name}</strong><small>{team.category?.name}</small></span><input type="checkbox" checked={memberships.has(team.id)} onChange={async event => { try { await api(`/teams/${team.id}/players/${player.id}`, { method: event.target.checked ? 'POST' : 'DELETE' }); refresh(); notify('Asignación actualizada'); } catch (err) { alert(err.message); } }} /></label>)}</div>; }

function Events({ api, team, notify }) { const { data, error, refresh } = useLoad(() => api(`/teams/${team.id}/events`)); const [editing, setEditing] = useState(null); if (!data) return <Loading />; return <div className="stack"><Button onClick={() => setEditing({})}><Icon>add</Icon> Actividad</Button><Error text={error} />{data.map(event => <div className="list-row" key={event.id}><span><strong>{event.title}</strong><small>{new Date(event.startsAt).toLocaleString('es-AR')}</small></span><div><button className="text-action" onClick={() => setEditing(event)}>Editar</button><button className="text-action danger" onClick={async () => { if (confirm('¿Eliminar actividad?')) { await api(`/events/${event.id}`, { method: 'DELETE' }); refresh(); } }}>Eliminar</button></div></div>)}{editing && <EventEditor api={api} team={team} event={editing.id ? editing : null} close={() => setEditing(null)} done={() => { setEditing(null); refresh(); notify('Agenda actualizada'); }} />}</div>; }
function EventEditor({ api, team, event, close, done }) { const [error, setError] = useState(''); return <Modal title={event ? 'Editar actividad' : 'Nueva actividad'} close={close}><form className="modal-form" onSubmit={async formEvent => { formEvent.preventDefault(); const data = Object.fromEntries(new FormData(formEvent.currentTarget)); data.notes = data.notes || null; try { await api(event ? `/events/${event.id}` : `/teams/${team.id}/events`, { method: event ? 'PATCH' : 'POST', body: JSON.stringify(data) }); done(); } catch (err) { setError(err.message); } }}><Field label="TÍTULO"><input name="title" defaultValue={event?.title} required /></Field><Field label="INICIO"><input name="startsAt" type="datetime-local" defaultValue={event ? new Date(event.startsAt).toISOString().slice(0, 16) : ''} required /></Field><Field label="FINALIZACIÓN"><input name="endsAt" type="datetime-local" defaultValue={event ? new Date(event.endsAt).toISOString().slice(0, 16) : ''} required /></Field><label className="field"><span className="eyebrow">NOTAS</span><textarea name="notes" defaultValue={event?.notes ?? ''} /></label><Error text={error} /><button className="primary">Guardar</button></form></Modal>; }

function Attendance({ api, team, notify }) { const { data, refresh } = useLoad(() => api(`/teams/${team.id}/attendance`)); const [edit, setEdit] = useState(null); if (!data) return <Loading />; return <div className="stack"><Button onClick={() => setEdit({})}><Icon>add_task</Icon> Tomar asistencia</Button>{data.map(session => <button className="list-row selectable" key={session.id} onClick={() => setEdit(session)}><span><strong>{new Date(session.date).toLocaleDateString('es-AR')}</strong><small>{session.records.length} registros</small></span><Icon>chevron_right</Icon></button>)}{edit && <AttendanceEditor api={api} team={team} session={edit.id ? edit : null} close={() => setEdit(null)} done={() => { setEdit(null); refresh(); notify('Asistencia guardada'); }} />}</div>; }
function AttendanceEditor({ api, team, session, close, done }) { const { data: players } = useLoad(() => api('/players')); const [records, setRecords] = useState(() => Object.fromEntries((session?.records || []).map(x => [x.playerId, x.status]))); const [error, setError] = useState(''); if (!players) return <Modal title="Asistencia" close={close}><Loading /></Modal>; const roster = players.filter(x => x.teams.some(t => t.teamId === team.id)); const setStatus = (id, status) => setRecords({ ...records, [id]: status }); return <Modal title="Asistencia" close={close}><form className="modal-form" onSubmit={async event => { event.preventDefault(); try { const body = { records: roster.map(p => ({ playerId: p.id, status: records[p.id] || 'PRESENT' })) }; if (session) await api(`/attendance/${session.id}`, { method: 'PUT', body: JSON.stringify(body) }); else await api(`/teams/${team.id}/attendance`, { method: 'POST', body: JSON.stringify({ ...body, date: new FormData(event.currentTarget).get('date') }) }); done(); } catch (err) { setError(err.message); } }}><Field label="FECHA"><input name="date" type="date" defaultValue={dateInput(session?.date)} disabled={Boolean(session)} required /></Field>{roster.map(player => <div className="attendance-row" key={player.id}><strong>{player.name}</strong><select value={records[player.id] || 'PRESENT'} onChange={e => setStatus(player.id, e.target.value)}><option value="PRESENT">Presente</option><option value="ABSENT">Ausente</option><option value="EXCUSED">Justificado</option></select></div>)}<Error text={error} /><button className="primary">Guardar asistencia</button></form></Modal>; }

function Statistics({ api, team }) { const { data, error } = useLoad(() => api(`/teams/${team.id}/statistics?months=6`)); if (!data) return <Loading />; const summary = data.summary || {}; return <div className="stack"><Error text={error} /><div className="stats-grid"><Stat label="Asistencia" value={`${Math.round(summary.attendanceRate || 0)}%`} /><Stat label="Presentes" value={summary.present || 0} /><Stat label="Ausentes" value={summary.absent || 0} /><Stat label="Justificados" value={summary.excused || 0} /></div>{(data.months || []).map(month => <div className="list-row" key={month.key}><span>{month.label || month.key}</span><strong>{Math.round(month.attendanceRate || 0)}%</strong></div>)}<span className="eyebrow">DETALLE POR JUGADOR</span>{(data.players || []).map(player => <div className="list-row" key={player.id}><span><strong>{player.name}</strong><small>{player.present || 0} presentes · {player.absent || 0} ausentes</small></span><strong>{Math.round(player.attendanceRate || 0)}%</strong></div>)}</div>; }
function Stat({ label, value }) { return <div className="card stat"><small>{label}</small><strong>{value}</strong></div>; }

function Plan({ api, team, notify }) { const { data, refresh } = useLoad(() => api(`/teams/${team.id}/plan`)); const [editing, setEditing] = useState(false); if (data === null) return <Loading />; const labels = [['strengths', 'Fortalezas'], ['improvementAreas', 'Aspectos a mejorar'], ['weeklyFocus', 'Objetivo semanal'], ['monthlyFocus', 'Objetivo mensual'], ['seasonFocus', 'Objetivo de temporada']]; return <div className="stack"><div className="toolbar"><Button onClick={() => setEditing(true)}><Icon>edit_note</Icon> {data ? 'Editar plan' : 'Crear plan'}</Button>{data && <button className="text-action danger" onClick={async()=>{if(confirm('¿Eliminar plan de trabajo?')){await api(`/teams/${team.id}/plan`,{method:'DELETE'});refresh();notify('Plan eliminado');}}}>Eliminar</button>}</div>{data ? labels.map(([key, label]) => data[key] && <section className="plan-section" key={key}><span className="eyebrow">{label}</span><p>{data[key]}</p></section>) : <div className="empty">Todavía no hay plan de trabajo.</div>}{editing && <PlanEditor api={api} team={team} plan={data} close={() => setEditing(false)} done={() => { setEditing(false); refresh(); notify('Plan actualizado'); }} />}</div>; }
function PlanEditor({ api, team, plan, close, done }) { const [error, setError] = useState(''); const fields = [['strengths', 'FORTALEZAS'], ['improvementAreas', 'ASPECTOS A MEJORAR'], ['weeklyFocus', 'OBJETIVO SEMANAL'], ['monthlyFocus', 'OBJETIVO MENSUAL'], ['seasonFocus', 'OBJETIVO DE TEMPORADA']]; return <Modal title="Plan de trabajo" close={close}><form className="modal-form" onSubmit={async event => { event.preventDefault(); try { await api(`/teams/${team.id}/plan`, { method: 'PUT', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); done(); } catch (err) { setError(err.message); } }}>{fields.map(([name, label]) => <label className="field" key={name}><span className="eyebrow">{label}</span><textarea name={name} defaultValue={plan?.[name] ?? ''} /></label>)}<Error text={error} /><button className="primary">Guardar plan</button></form></Modal>; }

function TeamStaff({ api, team, notify }) { const { data: assigned, refresh } = useLoad(() => api(`/teams/${team.id}/staff`)); const { data: users } = useLoad(() => api('/users')); if (!assigned || !users) return <Loading />; const ids = new Set(assigned.map(x => x.id)); return <div className="stack">{users.filter(user => user.role !== 'DIRECTOR').map(user => <label className="list-row" key={user.id}><span><strong>{user.name}</strong><small>{roles[user.role]}</small></span><input type="checkbox" checked={ids.has(user.id)} onChange={async event => { await api(`/teams/${team.id}/staff/${user.id}`, { method: event.target.checked ? 'PUT' : 'DELETE' }); refresh(); notify('Personal actualizado'); }} /></label>)}</div>; }

function ProgressNotes({ api, player, notify }) { const { data, refresh } = useLoad(() => api(`/players/${player.id}/progress-notes`)); const [create, setCreate] = useState(false); if (!data) return <Loading />; return <div className="stack"><Button onClick={() => setCreate(true)}><Icon>note_add</Icon> Seguimiento</Button>{data.map(note => <article className="card" key={note.id}><strong>{note.period === 'WEEKLY' ? 'Semanal' : 'Mensual'} · {new Date(note.periodStart).toLocaleDateString('es-AR')}</strong><p>{note.comment}</p><small>{note.author?.name}</small></article>)}{create && <ProgressEditor api={api} player={player} close={() => setCreate(false)} done={() => { setCreate(false); refresh(); notify('Seguimiento registrado'); }} />}</div>; }
function ProgressEditor({ api, player, close, done }) { const [error, setError] = useState(''); return <Modal title="Seguimiento deportivo" close={close}><form className="modal-form" onSubmit={async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); for (const key of ['overallScore', 'effort', 'shootingQuality', 'defenseQuality', 'offenseQuality', 'physicalState']) if (data[key] !== '') data[key] = Number(data[key]); else delete data[key]; try { await api(`/players/${player.id}/progress-notes`, { method: 'POST', body: JSON.stringify(data) }); done(); } catch (err) { setError(err.message); } }}><Field label="PERÍODO"><select name="period"><option value="WEEKLY">Semanal</option><option value="MONTHLY">Mensual</option></select></Field><Field label="INICIO DEL PERÍODO"><input name="periodStart" type="date" defaultValue={dateInput()} /></Field><label className="field"><span className="eyebrow">COMENTARIO DEPORTIVO</span><textarea name="comment" required /></label><Field label="PUNTAJE GENERAL (0–10)"><input name="overallScore" type="number" min="0" max="10" step="0.1" /></Field><Field label="ESFUERZO (0–100)"><input name="effort" type="number" min="0" max="100" /></Field><Error text={error} /><button className="primary">Guardar</button></form></Modal>; }

export function StaffWorkspace({ api, notify }) { const { data: users, refresh } = useLoad(() => api('/users')); const { data: invitations, refresh: refreshInvitations } = useLoad(() => api('/users/invitations')); const [invite, setInvite] = useState(false); if (!users || !invitations) return <Loading />; return <><header className="page-head"><div><span className="eyebrow">ORGANIZACIÓN</span><h1>Personal</h1><p className="subtitle">Invitaciones, roles y miembros de la organización.</p></div><Button onClick={() => setInvite(true)}><Icon>person_add</Icon> Invitar</Button></header><div className="list staff-list">{users.map(user => <div className="card list-row" key={user.id}><span><strong>{user.name}</strong><small>{user.email}</small></span>{user.role === 'DIRECTOR' ? <span className="role-label">Director</span> : <select value={user.role} onChange={async event => { await api(`/users/${user.id}/role`, { method: 'PATCH', body: JSON.stringify({ role: event.target.value }) }); refresh(); notify('Rol actualizado'); }}><option value="COACH">Entrenador</option><option value="MONITOR">Monitor</option></select>}</div>)}</div><p className="section eyebrow">INVITACIONES PENDIENTES</p><div className="list staff-list">{invitations.map(item => <div className="card list-row" key={item.id}><span><strong>{item.email}</strong><small>{roles[item.role]}</small></span><button className="text-action danger" onClick={async () => { await api(`/users/invitations/${item.id}`, { method: 'DELETE' }); refreshInvitations(); }}>Revocar</button></div>)}</div>{invite && <InviteStaff api={api} close={() => setInvite(false)} done={() => { setInvite(false); refreshInvitations(); notify('Invitación creada'); }} />}</>; }
function InviteStaff({ api, close, done }) { const [result, setResult] = useState(null); const [error, setError] = useState(''); return <Modal title="Invitar personal" close={close}>{result ? <div className="stack"><p>Invitación creada para <strong>{result.email}</strong>.</p>{result.invitationToken && <><p className="notice">Copiá este código para desarrollo:</p><code className="token">{result.invitationToken}</code></>}<Button onClick={done}>Cerrar</Button></div> : <form className="modal-form" onSubmit={async event => { event.preventDefault(); try { setResult(await api('/users/invitations', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) })); } catch (err) { setError(err.message); } }}><Field label="EMAIL"><input name="email" type="email" required /></Field><Field label="ROL"><select name="role"><option value="COACH">Entrenador</option><option value="MONITOR">Monitor</option></select></Field><Error text={error} /><button className="primary">Enviar invitación</button></form>}</Modal>; }

export function AccountWorkspace({ api, user, signOut }) { const [deleteOpen, setDeleteOpen] = useState(false); return <><header className="page-head"><div><span className="eyebrow">CUENTA</span><h1>Perfil</h1><p className="subtitle">{user.email} · {roles[user.role]}</p></div></header><section className="card profile-card"><div className="list-row"><span className="avatar avatar-large">{initials(user.name)}</span><span><strong>{user.name}</strong><small>{roles[user.role]}</small></span></div><button className="text-action danger" onClick={() => setDeleteOpen(true)}>Eliminar cuenta</button></section>{deleteOpen && <DeleteAccount api={api} user={user} close={() => setDeleteOpen(false)} signOut={signOut} />}</>; }
function DeleteAccount({ api, user, close, signOut }) { const confirmation = user.role === 'DIRECTOR' ? 'ELIMINAR ORGANIZACION' : 'ELIMINAR CUENTA'; const [error, setError] = useState(''); return <Modal title="Eliminar cuenta" close={close}><form className="modal-form" onSubmit={async event => { event.preventDefault(); try { await api('/auth/account', { method: 'DELETE', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); signOut(); } catch (err) { setError(err.message); } }}><p className="error">Esta acción no se puede deshacer.</p><Field label="CONTRASEÑA"><input name="password" type="password" minLength="10" required /></Field><Field label={`ESCRIBÍ ${confirmation}`}><input name="confirmation" required /></Field><Error text={error} /><button className="primary">Confirmar eliminación</button></form></Modal>; }
